scripts/contrib/ddimage: be explicit whether device doesn't exist or isn't writeable
Make the error messages a little more friendly.

Signed-off-by: Paul Eggleton <paul.eggleton@linux.intel.com>

diff --git a/scripts/contrib/ddimage b/scripts/contrib/ddimage
--- a/scripts/contrib/ddimage
+++ b/scripts/contrib/ddimage
@@ -132,8 +132,14 @@ if is_inuse $ACTUAL_DEVICE ; then
 fi
 
 
+if [ ! -e "$DEVICE" ]; then
+	echo "ERROR: Device $DEVICE does not exist"
+	usage
+	exit 1
+fi
+
 if [ ! -w "$DEVICE" ]; then
-	echo "ERROR: Device $DEVICE does not exist or is not writable"
+	echo "ERROR: Device $DEVICE is not writable"
 	usage
 	exit 1
 fi
