scripts/patchtest-commits: generalize script to accept patches
Instead of testing just merged commits, the script is now more general
accepting any number of input patches (mboxes). Results can now either
be stored in an output directory and/or merged into a branch (assemble
branch). Arguments are defined using getopts bash utility, making it much
cleaner.

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>

diff --git a/scripts/patchtest-commits b/scripts/patchtest-commits
--- a/scripts/patchtest-commits
+++ b/scripts/patchtest-commits
@@ -19,39 +19,102 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
-usage() {
-    echo -e "Runs patchtest starting at certain commit using the specified test suite"
-    echo -e "\$ $(basename $0) <since commit> <repository> <path to the discover start directory on the test suite>"
-    echo
-    echo -e "For example, test last 10 commits"
-    echo
-    echo -e "\$ $(basename $0) HEAD~10 $HOME/poky $HOME/patchtest-oe/tests"
-    echo
+function usage() {
+    cat << EOF
+\$ $(basename $0) -r <repodir> -s <startdir> -a <assemble branch> -b <start point> -o <outputdir> <patch> ... 
+
+where
+
+    <repodir>         : Repository
+    <startdir>        : Start directory for test discovery
+    <assemble branch> : Branch name to assemble patches (that can be merged), including results as git-notes
+    <start point>     : Start point for assemble branch. Defaults to $startpoint
+    <outputdir>       : Output directory patchtest results. Defaults to $outdir
+    <patch>           : Patch to test by patchtest
+EOF
+>&2
+
     exit 1
 }
 
-#Check the number of arguments
-NUMARGS=$#
-if [ ! $NUMARGS -eq 3 ]; then
-    usage
+repodir=''
+startdir=''
+assemblebranch=''
+startpoint='HEAD'
+outputdir='output'
+
+while getopts ":r:s:p:a:o:h" opt; do
+    case $opt in
+	r)
+	    repodir=$OPTARG
+	    ;;
+	s)
+	    startdir=$OPTARG
+	    ;;
+	p)
+	    startpoint=$OPTARG
+	    ;;
+	a)
+	    assemblebranch=$OPTARG
+	    ;;
+	o)
+	    outputdir=$OPTARG
+	    ;;
+	h)
+	    usage
+	    ;;
+	\?)
+	    echo "Invalid option: -$OPTARG" >&2
+	    usage
+	    ;;
+	:)
+	    echo "Option -$OPTARG requires an argument." >&2
+	    usage
+	    ;;
+    esac
+done
+shift $((OPTIND-1))
+
+[ ! -d $repodir ]  && { echo "Repository does not exit"; usage; }
+[ ! -d $startdir ] && { echo "Test suite starting directory does not exist"; usage; }
+[ ! -d $outputdir ] && { mkdir -p $outputdir; }
+
+# get current branch
+CURRENTB=$(git rev-parse --abbrev-ref HEAD)
+
+# create assemblebrach
+if [ -n "$assemblebranch" ]; then
+    git branch $assemblebranch $startpoint
 fi
 
-since=$1
-repo_dir=$(readlink -ev $2)
-start_dir=$(readlink -ev $3)
+for patch in "$@"; do
+    
+    echo -e "${patch}"
 
-[ ! -d $repo_dir ]  && { echo "Repository does not exit"; usage; }
-[ ! -d $start_dir ] && { echo "Test suite starting directory does not exist"; usage; }
+    # run patchtest
+    RESULTS=$(patchtest $patch --repo-dir $repodir --start-dir $startdir 2> /dev/null)
 
-old_dir=$PWD
+    # if output dir given, place results there inside mboxes as git notes
+    if [ -n "$outputdir" ]; then
+	patchfn=$(basename $patch)
+	echo "$RESULTS" > $outputdir/${patchfn}
+	echo -e "\tResults stored into '$outputdir'"
+    fi
 
-( cd $repo_dir;
-  for commit in $(git rev-list $since..HEAD --reverse); do
-     echo "Testing commit ${commit}"
-     git format-patch "$commit^1..$commit" --stdout | \
-	 patchtest - --base-commit "$commit^1" \
-		   --repo-dir $repo_dir \
-		   --start-dir $start_dir
-  done
-)
+    # if assemble branch give, try to assemble as many as possible
+    if [ -n "$assemblebranch" ]; then
+	# move the assemblebranch
+	git checkout $assemblebranch --quiet
 
+	# try patch merge
+	if git apply --check $patch; then
+	    git am --quiet $patch 2> /dev/null
+	    git notes add -m "$RESULTS"
+	    echo -e "\tPatch merged into '${assemblebranch}' with results as git-notes"
+	else
+	    echo -e "\tNot merged due to a merge-conflict"
+	fi
+	git checkout $CURRENTB --quiet
+	echo -e ""
+    fi
+done
